# This file created by conda-build 3.14.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Sep 15 14:04:44 2018
# ------------------------------------------------

package:
    name: xorg-xextproto
    version: 7.3.0
source:
    fn: xorg-xextproto-7.3.0.tar.bz2
    sha256: f3f4b23ac8db9c3a9e0d8edb591713f3d70ef9c3b175970dd8823dfc92aa5bb0
    url: https://www.x.org/releases/individual/proto/xextproto-7.3.0.tar.bz2
build:
    detect_binary_files_with_prefix: true
    number: '1002'
    string: h14c3975_1002
requirements:
    build:
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_3
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_3
        - libgcc-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 7.3.0 hdf63c60_0
        - pkg-config 0.29.2 h14c3975_1003
    host:
        - libgcc-ng 7.3.0 hdf63c60_0
        - xorg-util-macros 1.19.2 h14c3975_1001
    run:
        - libgcc-ng >=7.3.0
test:
    commands:
        - conda inspect linkages -p $PREFIX $PKG_NAME
about:
    home: https://www.x.org/
    license: MIT
    license_family: MIT
    license_file: COPYING
    summary: X.org extension C prototype files.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - pkgw
