using Hyperspecialize
println(:(@concretize Real Float32))
println(macroexpand(Main, :(@concretize Real Float32)))
println(:(@widen Real Float32))
println(macroexpand(Main, :(@widen Real Float32)))
println(:(@concretization Real))
println(macroexpand(Main, :(@concretization Real)))
println(:(@concretize (foo, Real) Float32))
println(macroexpand(Main, :(@concretize (foo, Real) Float32)))
println(:(@widen (foo, Real) Float32))
println(macroexpand(Main, :(@widen (foo, Real) Float32)))
println(:(@concretization (foo, Real)))
println(macroexpand(Main, :(@concretization (foo, Real))))
println(:(@replicable bar(x::@hyperspecialize((foo, Real))) = x))
println(macroexpand(Main, :(@replicable bar(x::@hyperspecialize((foo, Real))) = x)))
