# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly
matrix:
  allow_failures:
    - julia: nightly
git:
  depth: 999999
notifications:
  email: false
# script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'import Pkg; Pkg.add(Pkg.PackageSpec(path=pwd())); Pkg.build("AstroLib"); Pkg.test("AstroLib"; coverage=true)'
after_success:
 - julia -e 'import Pkg; Pkg.add("Documenter")'
 - julia -e 'import Pkg; cd(Pkg.dir("AstroLib")); include(joinpath("docs", "make.jl"))'
 - julia -e 'import Pkg; cd(Pkg.dir("AstroLib")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
