# This file created by conda-build 3.18.8
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Jul 20 01:58:17 2019
# ------------------------------------------------

package:
    name: cairo
    version: 1.16.0
source:
    sha256: 5e7b29b3f113ef870d1e3ecf8adf21f923396401604bda16d44be45e66052331
    url: http://cairographics.org/releases/cairo-1.16.0.tar.xz
build:
    number: '1002'
    run_exports:
        - cairo >=1.16.0,<2.0a0
    string: hfb77d84_1002
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - autoconf 2.69 pl526h14c3975_9
        - automake 1.16.1 pl526_1003
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_7
        - bzip2 1.0.8 h516909a_0
        - ca-certificates 2019.6.16 hecc5488_0
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_7
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - libtool 2.4.6 h14c3975_1002
        - m4 1.4.18 h14c3975_1001
        - make 4.2.1 h14c3975_2004
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1c h516909a_0
        - perl 5.26.2 h516909a_1006
        - pkg-config 0.29.2 h14c3975_1005
        - pthread-stubs 0.4 h14c3975_1001
        - python 3.7.3 h33d41f4_1
        - readline 8.0 hf8c457e_0
        - sqlite 3.29.0 hcee41ef_0
        - tk 8.6.9 hed695b0_1002
        - xcb-proto 1.13 py37h14c3975_1001
        - xorg-renderproto 0.11.1 h14c3975_1002
        - xorg-xproto 7.0.31 h14c3975_1007
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h516909a_1005
    host:
        - _libgcc_mutex 0.1 main
        - fontconfig 2.13.1 h86ecdb6_1001
        - freetype 2.9.1 he983fc9_1006
        - gettext 0.19.8.1 hc5be6a0_1002
        - glib 2.58.3 h6f030ca_1002
        - icu 64.2 he1b5a44_0
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.1.0 hdf63c60_0
        - libiconv 1.15 h516909a_1005
        - libpng 1.6.35 h84994c4_1002
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - libuuid 2.32.1 h14c3975_1000
        - libxcb 1.13 h14c3975_1002
        - libxml2 2.9.9 hee79883_2
        - pcre 8.41 hf484d3e_1003
        - pixman 0.38.0 h516909a_1003
        - pthread-stubs 0.4 h14c3975_1001
        - xorg-kbproto 1.0.7 h14c3975_1002
        - xorg-libice 1.0.10 h516909a_0
        - xorg-libsm 1.2.3 h84519dc_1000
        - xorg-libx11 1.6.8 h516909a_0
        - xorg-libxau 1.0.9 h14c3975_0
        - xorg-libxdmcp 1.1.3 h516909a_0
        - xorg-libxext 1.3.4 h516909a_0
        - xorg-libxrender 0.9.10 h516909a_1002
        - xorg-renderproto 0.11.1 h14c3975_1002
        - xorg-xextproto 7.3.0 h14c3975_1002
        - xorg-xproto 7.0.31 h14c3975_1007
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h516909a_1005
    run:
        - fontconfig >=2.13.1,<3.0a0
        - fontconfig >=2.13.1,<3.0a0
        - freetype >=2.9.1,<3.0a0
        - freetype >=2.9.1,<3.0a0
        - glib >=2.58.3,<3.0a0
        - icu >=64.2,<65.0a0
        - icu >=64.2,<65.0a0
        - libgcc-ng >=7.3.0
        - libpng >=1.6.35,<1.7.0a0
        - libpng >=1.6.35,<1.7.0a0
        - libxcb
        - pixman >=0.38.0,<0.39.0a0
        - pixman >=0.38.0,<0.39.0a0
        - xorg-libice
        - xorg-libsm
        - xorg-libx11
        - xorg-libxext
        - xorg-libxrender
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - cairo-trace --help
        - test -f $PREFIX/lib/libcairo.a
        - test -f $PREFIX/lib/libcairo.so
        - test -f $PREFIX/lib/libcairo-gobject.a
        - test -f $PREFIX/lib/libcairo-gobject.so
        - test -f $PREFIX/lib/libcairo-script-interpreter.a
        - test -f $PREFIX/lib/libcairo-script-interpreter.so
        - test -f $PREFIX/lib/pkgconfig/cairo-xlib.pc
        - test -f $PREFIX/include/cairo/cairo.h
        - grep -q "CAIRO_HAS_FC_FONT 1" $PREFIX/include/cairo/cairo-features.h
about:
    dev_url: https://gitlab.freedesktop.org/cairo/cairo
    doc_url: https://www.cairographics.org/documentation/
    home: http://cairographics.org/
    license: LGPL 2.1 or MPL 1.1
    license_file: COPYING
    summary: Cairo is a 2D graphics library with support for multiple output devices.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - jakirkham
        - ocefpaf
        - pkgw
