const DEFAULT_COMPRESSION_SAMPLING_RATIO = 1.0
const DEFAULT_QUANTIZAION_K = 2
const DEFAULT_QUANTIZATION_M = 1
const DEFAULT_QUANTIZATION_METHOD = :pq
const DEFAULT_QUANTIZATION_DISTANCE = Distances.SqEuclidean()
