language: julia

os:
  - linux
  - osx

julia:
  - 1.1.1
  - nightly

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: true

env:
  global:
    - DOCUMENTER_DEBUG=true

script:
  - julia --color=yes -e 'using Pkg; Pkg.build()'
  - julia --check-bounds=yes --color=yes -e 'using Pkg; Pkg.test(coverage=true)'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - julia --project=docs/ -e 'import Pkg; Pkg.add("Documenter")'
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
