QT.webenginecore_private.VERSION = 5.12.1
QT.webenginecore_private.name = QtWebEngineCore
QT.webenginecore_private.module =
QT.webenginecore_private.libs = $$QT_MODULE_LIB_BASE
QT.webenginecore_private.includes = $$QT_MODULE_INCLUDE_BASE/QtWebEngineCore/5.12.1 $$QT_MODULE_INCLUDE_BASE/QtWebEngineCore/5.12.1/QtWebEngineCore
QT.webenginecore_private.frameworks =
QT.webenginecore_private.depends = webenginecore
QT.webenginecore_private.uses =
QT.webenginecore_private.module_config = v2 internal_module
QT.webenginecore_private.enabled_features = webengine-alsa webengine-bison webengine-flex webengine-gperf webengine-host-pkg-config webengine-pepper-plugins webengine-printing-and-pdf webengine-python2 webengine-system-dbus webengine-system-fontconfig webengine-system-freetype webengine-system-glib webengine-system-glibc webengine-system-khr webengine-system-libdrm webengine-system-ninja webengine-system-nss webengine-system-png webengine-system-x11 webengine-system-xcomposite webengine-system-xcursor webengine-system-xi webengine-system-xrandr webengine-system-xtst webengine-system-zlib webengine-ui-delegates webengine-v8-snapshot webengine-v8-snapshot-support webengine-webrtc
QT.webenginecore_private.disabled_features = webengine-embedded-build webengine-arm-thumb webengine-kerberos webengine-poppler-cpp webengine-proprietary-codecs webengine-pulseaudio webengine-sanitizer webengine-system-ffmpeg webengine-system-gn webengine-system-harfbuzz webengine-system-icu webengine-system-jpeg webengine-system-jsoncpp webengine-system-lcms2 webengine-system-libevent webengine-system-libvpx webengine-system-libwebp webengine-system-libxml2 webengine-system-minizip webengine-system-opus webengine-system-protobuf webengine-system-re2 webengine-system-snappy webengine-testsupport webengine-win-compiler64 webengine-winversion
QMAKE_LIBS_WEBENGINE_DBUS = /opt/anaconda1anaconda2anaconda3/lib/libdbus-1.so
QMAKE_INCDIR_WEBENGINE_DBUS = /opt/anaconda1anaconda2anaconda3/include/dbus-1.0 /opt/anaconda1anaconda2anaconda3/lib/dbus-1.0/include
QMAKE_LIBS_WEBENGINE_FONTCONFIG = /opt/anaconda1anaconda2anaconda3/lib/libfontconfig.so /opt/anaconda1anaconda2anaconda3/lib/libfreetype.so
QMAKE_INCDIR_WEBENGINE_FONTCONFIG = /opt/anaconda1anaconda2anaconda3/include /opt/anaconda1anaconda2anaconda3/include/uuid /opt/anaconda1anaconda2anaconda3/include/libxml2 /opt/anaconda1anaconda2anaconda3/include /opt/anaconda1anaconda2anaconda3/include/freetype2
QMAKE_LIBS_WEBENGINE_FREETYPE = /opt/anaconda1anaconda2anaconda3/lib/libfreetype.so
QMAKE_INCDIR_WEBENGINE_FREETYPE = /opt/anaconda1anaconda2anaconda3/include/freetype2
QMAKE_LIBS_WEBENGINE_GLIB = /opt/anaconda1anaconda2anaconda3/lib/libglib-2.0.so
QMAKE_INCDIR_WEBENGINE_GLIB = /opt/anaconda1anaconda2anaconda3/include/glib-2.0 /opt/anaconda1anaconda2anaconda3/lib/glib-2.0/include /opt/anaconda1anaconda2anaconda3/include
QMAKE_LIBS_WEBENGINE_LIBDRM = /opt/anaconda1anaconda2anaconda3/bin/../x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64/libdrm.so
QMAKE_INCDIR_WEBENGINE_LIBDRM = /opt/anaconda1anaconda2anaconda3/bin/../x86_64-conda_cos6-linux-gnu/sysroot/usr/include /opt/anaconda1anaconda2anaconda3/bin/../x86_64-conda_cos6-linux-gnu/sysroot/usr/include/libdrm
QMAKE_LIBS_WEBENGINE_NSS = /opt/anaconda1anaconda2anaconda3/lib/libnss3.so /opt/anaconda1anaconda2anaconda3/lib/libnssutil3.so /opt/anaconda1anaconda2anaconda3/lib/libsmime3.so /opt/anaconda1anaconda2anaconda3/lib/libssl3.so /opt/anaconda1anaconda2anaconda3/lib/libsoftokn3.so /opt/anaconda1anaconda2anaconda3/lib/libplds4.so /opt/anaconda1anaconda2anaconda3/lib/libplc4.so /opt/anaconda1anaconda2anaconda3/lib/libnspr4.so
QMAKE_INCDIR_WEBENGINE_NSS = /opt/anaconda1anaconda2anaconda3/include/nss /opt/anaconda1anaconda2anaconda3/include/nspr
QMAKE_LIBS_WEBENGINE_PNG = /opt/anaconda1anaconda2anaconda3/lib/libpng16.so /opt/anaconda1anaconda2anaconda3/lib/libz.so
QMAKE_INCDIR_WEBENGINE_PNG = /opt/anaconda1anaconda2anaconda3/include/libpng16 /opt/anaconda1anaconda2anaconda3/include
QMAKE_LIBS_WEBENGINE_X11 = /opt/anaconda1anaconda2anaconda3/bin/../x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64/libX11.so
QMAKE_INCDIR_WEBENGINE_X11 = /opt/anaconda1anaconda2anaconda3/include /opt/anaconda1anaconda2anaconda3/bin/../x86_64-conda_cos6-linux-gnu/sysroot/usr/include
QMAKE_LIBS_WEBENGINE_XCOMPOSITE = /opt/anaconda1anaconda2anaconda3/bin/../x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64/libXcomposite.so
QMAKE_INCDIR_WEBENGINE_XCOMPOSITE = /opt/anaconda1anaconda2anaconda3/include /opt/anaconda1anaconda2anaconda3/bin/../x86_64-conda_cos6-linux-gnu/sysroot/usr/include
QMAKE_LIBS_WEBENGINE_XCURSOR = /opt/anaconda1anaconda2anaconda3/bin/../x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64/libXcursor.so
QMAKE_INCDIR_WEBENGINE_XCURSOR = /opt/anaconda1anaconda2anaconda3/include /opt/anaconda1anaconda2anaconda3/bin/../x86_64-conda_cos6-linux-gnu/sysroot/usr/include
QMAKE_LIBS_WEBENGINE_XI = /opt/anaconda1anaconda2anaconda3/bin/../x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64/libXi.so
QMAKE_INCDIR_WEBENGINE_XI = /opt/anaconda1anaconda2anaconda3/include /opt/anaconda1anaconda2anaconda3/bin/../x86_64-conda_cos6-linux-gnu/sysroot/usr/include
QMAKE_LIBS_WEBENGINE_XRANDR = /opt/anaconda1anaconda2anaconda3/bin/../x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64/libXrandr.so
QMAKE_INCDIR_WEBENGINE_XRANDR = /opt/anaconda1anaconda2anaconda3/include /opt/anaconda1anaconda2anaconda3/bin/../x86_64-conda_cos6-linux-gnu/sysroot/usr/include
QMAKE_LIBS_WEBENGINE_XTST = /opt/anaconda1anaconda2anaconda3/bin/../x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64/libXtst.so
QMAKE_INCDIR_WEBENGINE_XTST = /opt/anaconda1anaconda2anaconda3/include /opt/anaconda1anaconda2anaconda3/bin/../x86_64-conda_cos6-linux-gnu/sysroot/usr/include
QMAKE_LIBS_WEBENGINE_ZLIB = /opt/anaconda1anaconda2anaconda3/lib/libz.so
QMAKE_INCDIR_WEBENGINE_ZLIB = /opt/anaconda1anaconda2anaconda3/include
