QT.multimedia_private.VERSION = 5.12.1
QT.multimedia_private.name = QtMultimedia
QT.multimedia_private.module =
QT.multimedia_private.libs = $$QT_MODULE_LIB_BASE
QT.multimedia_private.includes = $$QT_MODULE_INCLUDE_BASE/QtMultimedia/5.12.1 $$QT_MODULE_INCLUDE_BASE/QtMultimedia/5.12.1/QtMultimedia
QT.multimedia_private.frameworks =
QT.multimedia_private.depends = core_private gui_private multimedia
QT.multimedia_private.uses =
QT.multimedia_private.module_config = v2 internal_module
QT.multimedia_private.enabled_features = alsa gstreamer_1_0 gstreamer gstreamer_app gstreamer_encodingprofiles linux_v4l
QT.multimedia_private.disabled_features = directshow directshow-player evr gpu_vivante gstreamer_0_10 gstreamer_photography openal pulseaudio resourcepolicy wasapi wmf wmf-player wmsdk wshellitem
QMAKE_LIBS_ALSA = /opt/anaconda1anaconda2anaconda3/x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64/libasound.so
QMAKE_LIBS_GSTREAMER = /opt/anaconda1anaconda2anaconda3/lib/libgstaudio-1.0.so /opt/anaconda1anaconda2anaconda3/lib/libgstvideo-1.0.so /opt/anaconda1anaconda2anaconda3/lib/libgstbase-1.0.so /opt/anaconda1anaconda2anaconda3/lib/libgstpbutils-1.0.so /opt/anaconda1anaconda2anaconda3/lib/libgstreamer-1.0.so /opt/anaconda1anaconda2anaconda3/lib/libgobject-2.0.so /opt/anaconda1anaconda2anaconda3/lib/libglib-2.0.so
QMAKE_INCDIR_GSTREAMER = /opt/anaconda1anaconda2anaconda3/include/gstreamer-1.0 /opt/anaconda1anaconda2anaconda3/include /opt/anaconda1anaconda2anaconda3/include/glib-2.0 /opt/anaconda1anaconda2anaconda3/lib/glib-2.0/include /opt/anaconda1anaconda2anaconda3/include
QMAKE_DEPENDS_GSTREAMER_APP_CC = GSTREAMER
QMAKE_DEPENDS_GSTREAMER_APP_LD = GSTREAMER
QMAKE_LIBS_GSTREAMER_APP = /opt/anaconda1anaconda2anaconda3/lib/libgstapp-1.0.so
