QT.core_private.VERSION = 5.12.1
QT.core_private.name = QtCore
QT.core_private.module =
QT.core_private.libs = $$QT_MODULE_LIB_BASE
QT.core_private.includes = $$QT_MODULE_INCLUDE_BASE/QtCore/5.12.1 $$QT_MODULE_INCLUDE_BASE/QtCore/5.12.1/QtCore
QT.core_private.frameworks =
QT.core_private.depends = core
QT.core_private.uses =
QT.core_private.module_config = v2 internal_module
QT.core_private.enabled_features = clock-gettime datetimeparser dlopen doubleconversion futimens glib icu inotify linkat poll_ppoll sha3-fast
QT.core_private.disabled_features = etw futimes getauxval getentropy posix-libiconv gnu-libiconv iconv journald lttng poll_poll poll_pollts poll_select renameat2 slog2 statx syslog system-doubleconversion system-pcre2
QMAKE_LIBS_LIBRT = /opt/anaconda1anaconda2anaconda3/x86_64-conda_cos6-linux-gnu/sysroot/usr/lib/librt.so
QMAKE_LIBS_LIBDL = /opt/anaconda1anaconda2anaconda3/x86_64-conda_cos6-linux-gnu/sysroot/usr/lib/libdl.so
QMAKE_LIBS_GLIB = /opt/anaconda1anaconda2anaconda3/lib/libgthread-2.0.so /opt/anaconda1anaconda2anaconda3/lib/libglib-2.0.so
QMAKE_INCDIR_GLIB = /opt/anaconda1anaconda2anaconda3/include /opt/anaconda1anaconda2anaconda3/include/glib-2.0 /opt/anaconda1anaconda2anaconda3/lib/glib-2.0/include /opt/anaconda1anaconda2anaconda3/include
QMAKE_DEPENDS_ICU_CC = LIBDL
QMAKE_DEPENDS_ICU_LD = LIBDL
QMAKE_LIBS_ICU = /opt/anaconda1anaconda2anaconda3/lib/libicui18n.so /opt/anaconda1anaconda2anaconda3/lib/libicuuc.so /opt/anaconda1anaconda2anaconda3/lib/libicudata.so
QMAKE_LIBS_LIBATOMIC = 
