# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Apr 25 03:39:41 2019
# ------------------------------------------------

package:
    name: kiwisolver
    version: 1.1.0
source:
    sha256: 53eaed412477c836e1b9522c19858a8557d6e595077830146182225613b11a75
    url: https://pypi.io/packages/source/k/kiwisolver/kiwisolver-1.1.0.tar.gz
build:
    number: '0'
    script: /home/conda/feedstock_root/build_artifacts/kiwisolver_1556163736775/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py37hc9558a2_0
requirements:
    build:
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_3
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_3
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_3
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
    host:
        - bzip2 1.0.6 h14c3975_1002
        - ca-certificates 2019.3.9 hecc5488_0
        - certifi 2019.3.9 py37_0
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1b h14c3975_1
        - pip 19.1 py37_0
        - python 3.7.3 h5b0a415_0
        - readline 7.0 hf8c457e_1001
        - setuptools 41.0.1 py37_0
        - sqlite 3.26.0 h67949de_1001
        - tk 8.6.9 h84994c4_1001
        - wheel 0.33.1 py37_0
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h14c3975_1004
    run:
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
        - python >=3.7,<3.8.0a0
test:
    imports:
        - kiwisolver
about:
    home: https://github.com/nucleic/kiwi
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: A fast implementation of the Cassowary constraint solver
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - MatthieuDartiailh
        - blink1073
        - ericdill
        - licode
        - ocefpaf
        - sccolbert
        - tacaswell
