# This file created by conda-build 3.13.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Aug 30 19:19:30 2018
# ------------------------------------------------

package:
    name: libuuid
    version: 2.32.1
source:
    fn: libuuid-2.32.1.tar.gz
    sha256: 3bbf9f3d4a33d6653cf0f7e4fc422091b6a38c3b1195c0ee716c67148a1a7122
    url: https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v2.32/util-linux-2.32.1.tar.gz
build:
    number: '1000'
    run_exports:
        - libuuid >=2.32.1,<3.0a0
    string: h14c3975_1000
requirements:
    build:
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_3
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_3
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
    host:
        - libgcc-ng 8.2.0 hdf63c60_1
    run:
        - libgcc-ng >=7.3.0
test:
    commands:
        - test -f ${PREFIX}/lib/libuuid.a
        - conda inspect linkages libuuid
about:
    home: http://sourceforge.net/projects/libuuid/
    license: BSD 3-Clause
    summary: Portable uuid C library.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
