# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Mar 19 02:20:29 2019
# ------------------------------------------------

package:
    name: xorg-libxdmcp
    version: 1.1.3
source:
    fn: xorg-libXdmcp-1.1.3.tar.bz2
    sha256: 20523b44aaa513e17c009e873ad7bbc301507a3224c232610ce2e099011c6529
    url: https://www.x.org/releases/individual/lib/libXdmcp-1.1.3.tar.bz2
build:
    detect_binary_files_with_prefix: true
    number: '0'
    string: h516909a_0
requirements:
    build:
        - autoconf 2.69 pl526h14c3975_9
        - automake 1.16.1 pl526_1003
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_6
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_6
        - gettext 0.19.8.1 h9745a5d_1001
        - libffi 3.2.1 hf484d3e_1005
        - libgcc-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 7.3.0 hdf63c60_0
        - libtool 2.4.6 h14c3975_1002
        - m4 1.4.18 h14c3975_1001
        - make 4.2.1 h14c3975_2004
        - perl 5.26.2 h14c3975_1002
        - pkg-config 0.29.2 h14c3975_1005
    host:
        - libgcc-ng 7.3.0 hdf63c60_0
        - xorg-util-macros 1.19.2 h14c3975_1001
        - xorg-xproto 7.0.31 h14c3975_1007
    run:
        - libgcc-ng >=7.3.0
test:
    commands:
        - test -f $PREFIX/lib/libXdmcp.so
        - conda inspect linkages -p $PREFIX $PKG_NAME
about:
    home: https://www.x.org/
    license: MIT
    license_family: MIT
    license_file: COPYING
    summary: The X-windows display manager client protocol library.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - pkgw
