# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Feb 11 18:12:52 2019
# ------------------------------------------------

package:
    name: xorg-libxau
    version: 1.0.9
source:
    fn: xorg-libXau-1.0.9.tar.bz2
    sha256: ccf8cbf0dbf676faa2ea0a6d64bcc3b6746064722b606c8c52917ed00dcb73ec
    url: https://www.x.org/releases/individual/lib/libXau-1.0.9.tar.bz2
build:
    detect_binary_files_with_prefix: true
    number: '0'
    string: h14c3975_0
requirements:
    build:
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_6
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_6
        - libgcc-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 7.3.0 hdf63c60_0
        - pkg-config 0.29.2 h14c3975_1004
    host:
        - libgcc-ng 7.3.0 hdf63c60_0
        - xorg-util-macros 1.19.2 h14c3975_1001
        - xorg-xproto 7.0.31 h14c3975_1007
    run:
        - libgcc-ng >=7.3.0
test:
    commands:
        - test -f $PREFIX/lib/libXau.so
        - conda inspect linkages -p $PREFIX $PKG_NAME
about:
    home: https://www.x.org/
    license: MIT
    license_family: MIT
    license_file: COPYING
    summary: A simple X Windows authentication protocol.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - pkgw
