# This file created by conda-build 3.14.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Sep 15 14:00:14 2018
# ------------------------------------------------

package:
    name: xorg-xproto
    version: 7.0.31
source:
    fn: xorg-xproto-7.0.31.tar.bz2
    sha256: c6f9747da0bd3a95f86b17fb8dd5e717c8f3ab7f0ece3ba1b247899ec1ef7747
    url: https://www.x.org/releases/individual/proto/xproto-7.0.31.tar.bz2
build:
    detect_binary_files_with_prefix: true
    number: '1007'
    string: h14c3975_1007
requirements:
    build:
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_3
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_3
        - libgcc-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 7.3.0 hdf63c60_0
        - pkg-config 0.29.2 h14c3975_1003
    host:
        - libgcc-ng 7.3.0 hdf63c60_0
        - xorg-util-macros 1.19.2 h14c3975_1001
    run:
        - libgcc-ng >=7.3.0
test:
    commands:
        - conda inspect linkages -p $PREFIX $PKG_NAME
about:
    home: https://www.x.org/
    license: MIT
    license_family: MIT
    license_file: COPYING
    summary: Core X Windows C prototypes.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - pkgw
