# This file created by conda-build 3.17.5
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/hdf5-1.10.4-on-linux_64, last modified Wed Dec 19 17:45:30 2018
# ------------------------------------------------

package:
    name: hdf5
    version: 1.10.4
source:
    patches:
        - test_Makefile.in.patch
    sha256: 8f60dc4dd6ab5fcd23c750d1dc5bca3d0453bdce5c8cdaf0a4a61a9d1122adb2
    url: https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.4/src/hdf5-1.10.4.tar.gz
build:
    number: '0'
    run_exports:
        - hdf5 >=1.10.4,<1.10.5.0a0
    string: hb1b8bf9_0
requirements:
    build:
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_3
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_3
        - gfortran_impl_linux-64 7.3.0 hdf63c60_1
        - gfortran_linux-64 7.3.0 h553295d_3
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_3
        - libgcc-ng 8.2.0 hdf63c60_1
        - libgfortran-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - libtool 2.4.6 h7b6447c_5
        - make 4.2.1 h1bed415_1
    host:
        - libgcc-ng 8.2.0 hdf63c60_1
        - libgfortran-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - zlib 1.2.11 h7b6447c_3
    run:
        - libgcc-ng >=7.3.0
        - libgfortran-ng >=7,<8.0a0
        - libstdcxx-ng >=7.3.0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - command -v h5c++
        - command -v h5cc
        - command -v h5perf_serial
        - command -v h5redeploy
        - command -v h5fc
        - command -v gif2h5
        - command -v h52gif
        - command -v h5copy
        - command -v h5debug
        - command -v h5diff
        - command -v h5dump
        - command -v h5import
        - command -v h5jam
        - command -v h5ls
        - command -v h5mkgrp
        - command -v h5repack
        - command -v h5repart
        - command -v h5stat
        - command -v h5unjam
        - test -f $PREFIX/lib/libhdf5.a
        - test -f $PREFIX/lib/libhdf5.so
        - test -f $PREFIX/lib/libhdf5_cpp.a
        - test -f $PREFIX/lib/libhdf5_cpp.so
        - test -f $PREFIX/lib/libhdf5_hl.a
        - test -f $PREFIX/lib/libhdf5_hl.so
        - test -f $PREFIX/lib/libhdf5_hl_cpp.a
        - test -f $PREFIX/lib/libhdf5_hl_cpp.so
    files:
        - compound_fortran2003.f90
        - h5_cmprss.c
        - h5_cmprss.f90
        - h5tutr_cmprss.cpp
    requires:
        - gcc_linux-64 7.3.0.*
        - gfortran_linux-64 7.3.0.*
        - gxx_linux-64 7.3.0.*
about:
    description: 'HDF5 supports an unlimited variety of datatypes, and is designed
        for

        flexible and efficient I/O and for high volume and complex data.

        '
    dev_url: https://www.hdfgroup.org/HDF5/release/obtain5.html
    doc_url: https://www.hdfgroup.org/HDF5/doc/
    home: http://www.hdfgroup.org/HDF5/
    license: HDF5
    license_family: BSD
    license_file: COPYING
    summary: HDF5 is a data model, library, and file format for storing and managing
        data
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - astrofrog
        - gillins
        - groutr
        - jakirkham
        - marqh
        - msarahan
        - ocefpaf
