# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Mar 18 21:23:32 2019
# ------------------------------------------------

package:
    name: xorg-libxext
    version: 1.3.4
source:
    fn: xorg-libXext-1.3.4.tar.bz2
    sha256: 59ad6fcce98deaecc14d39a672cf218ca37aba617c9a0f691cac3bcd28edf82b
    url: https://www.x.org/releases/individual/lib/libXext-1.3.4.tar.bz2
build:
    detect_binary_files_with_prefix: true
    number: '0'
    string: h516909a_0
requirements:
    build:
        - autoconf 2.69 pl526h14c3975_9
        - automake 1.16.1 pl526_1003
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_6
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_6
        - gettext 0.19.8.1 h9745a5d_1001
        - libffi 3.2.1 hf484d3e_1005
        - libgcc-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 7.3.0 hdf63c60_0
        - libtool 2.4.6 h14c3975_1002
        - m4 1.4.18 h14c3975_1001
        - make 4.2.1 h14c3975_2004
        - perl 5.26.2 h14c3975_1002
        - pkg-config 0.29.2 h14c3975_1005
    host:
        - libgcc-ng 7.3.0 hdf63c60_0
        - libxcb 1.13 h14c3975_1002
        - pthread-stubs 0.4 h14c3975_1001
        - xorg-kbproto 1.0.7 h14c3975_1002
        - xorg-libx11 1.6.7 h14c3975_1000
        - xorg-libxau 1.0.9 h14c3975_0
        - xorg-libxdmcp 1.1.2 h14c3975_1007
        - xorg-util-macros 1.19.2 h14c3975_1001
        - xorg-xextproto 7.3.0 h14c3975_1002
        - xorg-xproto 7.0.31 h14c3975_1007
    run:
        - libgcc-ng >=7.3.0
        - xorg-libx11 1.6.*
        - xorg-xextproto
test:
    commands:
        - test -f $PREFIX/lib/libXext.so
        - conda inspect linkages -p $PREFIX $PKG_NAME
about:
    home: https://www.x.org/
    license: MIT
    license_family: MIT
    license_file: COPYING
    summary: The X.org extensions library.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - pkgw
